[project]
name = "llm-websearch"
version = "0.1.0"
description = "LLM plugin for web searching and deep searching."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "llm",
    "click",
    "httpx",
    "python-dotenv",
    "beautifulsoup4",
    "html2text",
    "pdfminer.six"
]

[project.entry-points.llm]
websearch = "llm_websearch"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
]
